[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
coinflip = "AJq49zQoJr8MjU1CHD6XietaT84YiQyRhAYM9FE74ApZ"
manager = "88ZpZY4cseY2fU2WY8u7hYyQSzp8t36iJSd4XcqfKh6V"
raffle = "7iKkN561Q2C5w9ooaf5U7LHnVtH3VyyErWiiUr1TJcRk"
robix = "9GaG1Kh8mdVMY3UZWbE3sYikwhiM8qyuup9GzgHUFxCh"
wheel = "A7tUzPVsRRmPLMAR16Qu8KCS6CS8RpiG3QanqGF83oDN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
